### ISSUE TITLE
About confidence output

### ISSUE THREAD

**Issue by yumlll** [PinataFarms/FEARTracker#5]
In the Demo app, how to judge the target is missing? The confidence output is always very high, regardless of whether the target is missing or not

**Comment by borsukvasyl** [comment]
Hi, you can use the same method as in academic benchmarks to detect the tracker's failure. We'll add failure detection to demo app later.

**Comment by Vujas-Eteph** [comment]
Hello!
Great work and a well-written paper!
I would like to follow up on the previous question because I have the same problem as @yumlll . When the target is no longer visible, the tracker continues to show a high confidence "score". Here, I would have expected a drop in confidence. Also, can you expand on the idea of detecting a tracker's failure? Or point to an example(academic benchmark)? 
I would be very grateful.

I wish you the best!

**Comment by jingjie-z** [comment]
excuse me, how do you deal with it?

**Comment by Vujas-Eteph** [comment]
Hi, I moved to another project
